name: demodezi
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  page_indicator: ^0.4.1
  lottie: ^2.0.0
  favorite_button: ^0.0.4
  givestarreviews: ^1.0.2
  editable_image: ^1.1.0
  flutter_rating_bar: ^4.0.1
  im_stepper: ^1.0.1+1
  timeline_tile: ^2.0.0
  timelines: ^0.1.0
  email_validator: ^2.1.17
  fluttertoast: ^8.0.9
  firebase_core: ^2.2.0
  firebase_auth: ^4.1.2
  firebase_messaging: ^14.1.0
  flutter_local_notifications: ^12.0.3
  flutter_stripe: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/images/ERGOWEAR.png
    - assets/images/LGBT.png
    - assets/images/NEIWAI.png
    - assets/images/SATURDAY TO SUNDAY.png
    - assets/images/UNDEEXPERT.png
    - assets/images/weekendbuddylogo.png
    - assets/images/abc.png
    - assets/images/Website scroll 11.png
    - assets/images/Website scroll 12.png
    - assets/images/Website scroll 15.png
    - assets/images/Website scroll 17.png
    - assets/images/Website scroll 18.png
    - assets/images/Website scroll 19.png
    - assets/images/Website scroll 20.png
    - assets/images/Dispatch.png
    - assets/images/packaging.png
    - assets/images/Return.png
    - assets/images/PAYMENT.png
    - assets/images/Websitescroll2.png
    - assets/images/text png.png
    - assets/images/text png 2.png
    - assets/images/text png 3.png
    - assets/images/myunde logo.png
    - assets/images/myunde logo 1.png
    - assets/images/trunk out els.png
    - assets/images/Tanktop Model.png
    - assets/images/t-shirts.png
    - assets/images/Website Background.png
    - assets/images/Website Background 1.png
    - assets/images/Website Background 500.3000.png
    - assets/images/Brief Button.png
    - assets/images/Trunk Button.png
    - assets/images/success.png
    - assets/images/slide-1.png
    - assets/images/slide-2.png
    - assets/images/slide-3.png
    - assets/images/slide-4.png
    - assets/images/slide-5.png
    - assets/images/slide-6.png
    - assets/images/slide-7.png
    - assets/images/Socks 1.png
    - assets/images/Socks 2.png
    - assets/images/Socks 3.png
    - assets/images/1 boxerBrief-01.png
    - assets/images/1 Brief Inner Elastic-01.png
    - assets/images/1 Brief Outer Elastic-01.png
    - assets/images/1 fashion Brief-01.png
    - assets/images/1 Fashion Trunk-01.png
    - assets/images/1 Jogger-01.png
    - assets/images/1 Pyjama.png
    - assets/images/1 Pyjama 2-01.png
    - assets/images/1 Pyjama 3-01.png
    - assets/images/1 Shorts-01.png
    - assets/images/1 tank top-01.png
    - assets/images/1 Trunk-01.png
    - assets/images/1 myunde.png
    - assets/images/1 Website scroll 19 (3) 2.png
    - assets/images/1 Website scroll 19 (3)-01.png
    - assets/images/1 Website scroll 19 (4).png
    - assets/images/1 Website scroll 19 (2)-01.png

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Aadhunik
      fonts:
        - asset: fonts/Aadhunik.ttf

    - family: Aadhunik Light
      fonts:
        - asset: fonts/Aadhunik Light.ttf

    - family: Acumin Variable Concept
      fonts:
        - asset: fonts/Acumin Variable Concept.ttf

    - family: Arial
      fonts:
        - asset: fonts/arial 1.ttf

    - family: Arial
      fonts:
        - asset: fonts/Arial 2.ttf

    - family: AtthiaDemoRegular
      fonts:
        - asset: fonts/AtthiaDemoRegular.ttf

    - family: Atthia Demo Sanserif
      fonts:
        - asset: fonts/AtthiaDemoSanserif.ttf

    - family: AtthiaDemoVintage
      fonts:
        - asset: fonts/AtthiaDemoVintage.ttf

    - family: Audiowide Regular 400
      fonts:
        - asset: fonts/Audiowide Regular 400.ttf

    - family: Bee Leave
      fonts:
        - asset: fonts/Bee Leave.ttf

    - family: book
      fonts:
        - asset: fonts/book.ttf

    - family: BRLNSDB
      fonts:
        - asset: fonts/BRLNSDB.ttf

    - family: Cambria
      fonts:
        - asset: fonts/Cambria.ttf

    - family: cambriab
      fonts:
        - asset: fonts/cambriab.ttf

    - family: CAMBRIAI
      fonts:
        - asset: fonts/CAMBRIAI.ttf

    - family: CAMBRIAZ
      fonts:
        - asset: fonts/CAMBRIAZ.ttf

    - family: COMIC
      fonts:
        - asset: fonts/COMIC.ttf

    - family: comici
      fonts:
        - asset: fonts/comici.ttf

    - family: ComicSansMS3
      fonts:
        - asset: fonts/ComicSansMS3.ttf

    - family: comicz
      fonts:
        - asset: fonts/comicz.ttf

    - family: cour
      fonts:
        - asset: fonts/cour.ttf

    - family: DEBUG FREE TRIAL
      fonts:
        - asset: fonts/DEBUG FREE TRIAL.ttf

    - family: design.graffiti.comicsansms
      fonts:
        - asset: fonts/design.graffiti.comicsansms.ttf

    - family: design.graffiti.comicsansmsgras
      fonts:
        - asset: fonts/design.graffiti.comicsansmsgras.ttf

    - family: Freehand521BT
      fonts:
        - asset: fonts/Freehand521BT.ttf

    - family: Maiandra GD Regular
      fonts:
        - asset: fonts/Maiandra GD Regular.ttf

    - family: Myriad Pro Bold
      fonts:
        - asset: fonts/Myriad Pro Bold.ttf

    - family: Myriad Pro Regular
      fonts:
        - asset: fonts/Myriad Pro Regular.ttf

    - family: Rosmatika (DEMO)
      fonts:
        - asset: fonts/Rosmatika (DEMO).ttf

    - family: SilentCaroline-1GlMg
      fonts:
        - asset: fonts/SilentCaroline-1GlMg.ttf

    - family: sitka-small-599
      fonts:
        - asset: fonts/sitka-small-599.ttf

    - family: sitka-small-652
      fonts:
        - asset: fonts/sitka-small-652.ttf

    - family: sitka-small-815
      fonts:
        - asset: fonts/sitka-small-815.ttf

    - family: SourceSerifPro-Bold
      fonts:
        - asset: fonts/SourceSerifPro-Bold.ttf

    - family: SourceSerifPro-Regular
      fonts:
        - asset: fonts/SourceSerifPro-Regular.ttf

    - family: SourceSerifPro-Semibold
      fonts:
        - asset: fonts/SourceSerifPro-Semibold.ttf

    - family: Velissa
      fonts:
        - asset: fonts/Velissa.ttf



    - family: Daviton DEMO
      fonts:
        - asset: fonts/Daviton DEMO.otf


    - family: Monea Alegante
      fonts:
        - asset: fonts/Monea Alegante.otf


    - family: BellGothicStd-Black
      fonts:
        - asset: fonts/BellGothicStd-Black.otf





  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
